name: Commit Stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gggotogithub/mycat-service
  VERSION: latest

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/main}}
    needs: [ build ]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
  
